### ISSUE TITLE
Make an astroplan slack 

### ISSUE THREAD

**Issue by eteq** [astroplanners/astroplan#10]
Inspired by @bmorris3's comment in #9 I thought I'd offer another option for our purposes: we could try making a [Slack](https://slack.com/) team.  The nice thing about slack is that it allows either e-mail like async discussion or real-time chat in the same context. I've used it for a couple science collaborations and it seems good as a replacement for e-mail/chat...  Should I make a slack team for us to try it?

**Comment by eteq** [comment]
Oh, and in case it's not clear, I'm thinking this might be better than gitter because of the online/offline thing: as @adrn said, gitter hasn't ended up getting used so much because there aren't people regularly there.  Slack (at least to me) is better about that because it works about as well real-time as it does in a more e-mail like way, so even if someone can't be online all the time it's still useful.

**Comment by bmorris3** [comment]
Sounds cool.

**Comment by eteq** [comment]
Although we'd want to commit to actually (at least try to) use it, though, @adrn @cdeil @ejeschke, and @jberlanga.  I get the impression this sort of small team is what it's designed for, but I'm guessing it sort of needs group buy-in to be useful.

**Comment by cdeil** [comment]
It's not clear to me yet what combination of Slack / Email / Gitter / Github comments is good for us ... there is a risk that things get too scattered.

But if one of you is willing to set it up, :+1: to try Slack for `astroplan` for a while and see how it works / if we like it.

**Comment by eteq** [comment]
alright, done: see https://astroplan.slack.com/ .  I guess let the best medium win ;)
