### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by cdeil** [astroplanners/astroplan#28]
I propose we drop Python 2 support for `astroplan`, i.e. make it a Python 3 only package from the start (i.e. the 0.1 release).

This is not a joke, I think it's about time for new packages. [The great migration has begun](http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/) and I started my first Python 3-only package a month ago ([ctapipe](https://cta-observatory.github.io/ctapipe/#what-is-ctapipe)) and the sky hasn't fallen on my head.

I don't want to argue and list pros / cons for this decision, I think most of us are well-aware.
Just one comment: The biggest con is that some potential users are on Python 2 now and for this reason might not use astroplan for now. I think that's OK, they'll start using it in the coming years after they've moved to Python 3.

@astroplanners/astroplanners-contributors – What do you think?

@ejeschke – Do you need Python 2 support for Subaru?

**Comment by ejeschke** [comment]
@cdeil, I think we should support python 2+3 for the first version.  I'm probably fine with switching to python 3 only in a later version.  The code is already 2 compatible and we could use all the help we can get testing it and getting feedback, so this would definitely argue for keeping 2 support for now, to get the larger user pool.  Many observatories are still stuck in 2-land.

Subaru is in the early stages of transition.  Some apps like ginga are already 3 compatible, but there is a lot of 2 code left.  I think for our use of this astroplan code 3  would be fine, but I'd still argue for 2 support for the reasons I outlined above.

**Comment by bmorris3** [comment]
I'm opposed to dropping 2. A bunch of astronomers that I know work in 2 and don't see a reason to switch to 3 (see [astrofrog's post on the state of the migration](http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/)), and I don't think they'd switch for astroplan.

**Comment by cdeil** [comment]
There doesn't seem to be support for dropping Python 2 support at this time.
Closing this issue for now ... but I might re-open it and ask again in a year or two...
