### ISSUE TITLE
Revisiting the API spec

### ISSUE THREAD

**Issue by bmorris3** [astroplanners/astroplan#47]
Since starting to code, some parts of the [API](https://github.com/astroplanners/astroplan/blob/master/dev/planning-example.py) haven't been discussed in a while, and @cdeil prompted me to start a discussion among @astroplanners/astroplanners-contributors about how we should modify/remove the API as it is now. 

First question: should we discard this document now? If not, we should update it.

**Comment by cdeil** [comment]
+1 to remove the file from the repo.
We should focus on getting the code and docs and test done.
Updating the API spec also is just extra work with almost no gain.

(@jberlanga should go through that document and copy & paste & update all relevant parts to the high-level docs though in #42)

**Comment by cdeil** [comment]
@bmorris3 – Can you please make a PR to remove the file?
And then if there's agreement we'll merge it in the hangout tonight.

**Comment by bmorris3** [comment]
I've done so in #68.

**Comment by eteq** [comment]
@bmorris3 : interestingly, it looks to me like merging #68 didn't close this.  I guess the text ``addresses #47`` isn't recognized by github... probably ``closes #47`` would have worked though?  Weird.
