### ISSUE TITLE
Gitter room

### ISSUE THREAD

**Issue by bmorris3** [astroplanners/astroplan#9]
Hey owners (@cdeil)– would you mind creating a [Gitter](https://gitter.im) room for astroplan? I think it would be a convenient way for @jberlanga and I (and all of you as well) to keep in touch for short questions.

**Comment by cdeil** [comment]
As far as I know, there's an Astropy Gitter room and it's almost unused.
(of I'm not using it correctly and am not seeing any messages from the past weeks)

I think it would be great if Astropy and affiliated package devs start using the Astropy Gitter room.
Especially with GSoC students should have a place to ask git / Python / Astropy questions.

So @bmorris3, my preference would be that you start using the Astropy one, and only if others start using it as well and it starts to get too much, we should make a separate one for Astroplan.

@eteq @astrofrog – Can you make a decision on https://github.com/astropy/astropy/pull/3695 ?

**Comment by adrn** [comment]
I used to leave it open in a tab, but found that no one else was every "online" -- I'll start hanging out in the astropy gitter room again!

**Comment by jberlanga** [comment]
How do you find the astropy gitter room?

**Comment by adrn** [comment]
https://gitter.im/astropy/astropy#

**Comment by bmorris3** [comment]
It's a great tool, I love having markdown in a chat. Thanks for recommending the astropy room, I'll use that and try to keep the tab open..
